# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import main.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=main.helpers.RandomFileName('avatar')),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='now_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='total_count',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='cash',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
