# Generated by Django 2.0a1 on 2017-10-10 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170919_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='users',
            field=models.ManyToManyField(through='main.UserScore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Merchandise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='lottery',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to='main.Lottery'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to=settings.AUTH_USER_MODEL),
        ),
    ]
