# Generated by Django 2.0a1 on 2017-10-28 19:59

from django.db import migrations, models
import main.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lottery_random_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/default/avatar.png', null=True, upload_to=main.helpers.RandomFileName('avatar')),
        ),
        migrations.AlterUniqueTogether(
            name='userscore',
            unique_together={('user', 'lottery')},
        ),
    ]
