# Generated by Django 2.0a1 on 2017-10-28 20:03

from django.db import migrations, models
import main.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171028_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/default/avatar.png', null=True, upload_to=main.helpers.RandomFileName('avatar')),
        ),
    ]
