# Generated by Django 2.0a1 on 2017-10-28 20:07

from django.db import migrations, models
import main.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171028_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default/avatar.png', null=True, upload_to=main.helpers.RandomFileName('avatar')),
        ),
    ]
